using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace Gui_WinFormApp
{

 

    public partial class ProductCard : UserControl
    {
      

        //AutoGenerated property

        private string _price;

        public string Price
        {
            set { _price = value; lblPrice.Text = value; }
            get { return _price; }
        }

        private string _title;

        public  string Title
        {
            get { return _title; }
            set { _title = value; lblTitle.Text = value; }
        }

        private string _desc;

        public string Desc 
        {
            get { return _desc; }
            set { _desc = value; lblDesc.Text = value; }
        }

      
        public ProductCard()
        {
            InitializeComponent();
        }

    }




}
